### ISSUE TITLE
More useful warning message for non-functional allele

### ISSUE THREAD

**Issue by andim** [yutanagano/tidytcells#49]
Currently when a non-functional V or J gene is detected, a warning message appears which is potentially confusing. The current warning states that the attempted fix is with the original allele. Instead one might simply warn the user that the gene is non-functional (but that no fix was done).

**Comment by yutanagano** [comment]
@andim, would the best fix for this issue be to simply omit the portion of the warning telling the user a best attempted fix in the case that the best attempted fix is identical to the input?

i.e. original warning:
```
UserWarning: Failed to standardize "TRAJ2" for species homosapiens: gene has no functional alleles. Attempted fix: "TRAJ2".
```

new warning:
```
UserWarning: Failed to standardize "TRAJ2" for species homosapiens: gene has no functional alleles.
```

But keep attempted fix messages where it is not identical to input:
```
UserWarning: Failed to standardize "TRAJ2-1" for species homosapiens: gene has no functional alleles. Attempted fix: "TRAJ2".
```

**Comment by andim** [comment]
This looks like a suitable solution to me!
